#!/bin/sh

# PROVIDE: defguard-proxy
# REQUIRE: NETWORKING wireguard
# KEYWORD: shutdown

. /etc/rc.subr

name="defguard_proxy"
rcvar=defguard_proxy_enable
command="/usr/local/bin/defguard-proxy"
config="/etc/defguard/proxy.toml"
start_cmd="${name}_proxy_start"

defguard_proxy_start() {
	${command} --config ${config} &
}

load_rc_config $name
run_rc_command "$1"
