#!/bin/sh
set -e

USERNAME=defguard

if ! id -u ${USERNAME} >/dev/null 2>&1
then
	pw user add -n ${USERNAME} -g nogroup -c "Defguard" -d /nonexistent -s /usr/sbin/nologin
fi

mkdir -p /etc/defguard
chown ${USERNAME}:${USERNAME} /etc/defguard
chmod 750 /etc/defguard
