#!/bin/sh
set -e

SERVICE_NAME='defguard-proxy'

case "${1}" in
1 | configure)
	if [ -x /usr/bin/systemctl ]; then
		/usr/bin/systemctl daemon-reload
		/usr/bin/systemctl enable ${SERVICE_NAME}
		/usr/bin/systemctl --no-block start ${SERVICE_NAME}
	fi
	;;
abort-upgrade | abort-remove | abort-deconfigure)
	if [ -x /usr/bin/systemctl ]; then
		/usr/bin/systemctl daemon-reload
		if /usr/bin/systemctl is-enabled ${SERVICE_NAME} >/dev/null 2>&1; then
			/usr/bin/systemctl start ${SERVICE_NAME} || true
		fi
	fi
	;;
esac
