name: Test cross build

on:
  push:
    branches:
       - cross

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    needs: [create-release]
    runs-on:
      - self-hosted
      - ${{ matrix.os }}
      - X64
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     build: [linux, linux-arm64, freebsd]
    #     include:
    #       - build: linux
    #         arch: amd64
    #         os: Linux
    #         target: x86_64-unknown-linux-gnu
    #       - build: linux-arm64
    #         arch: arm64
    #         os: Linux
    #         target: aarch64-unknown-linux-gnu
    #       - build: freebsd
    #         arch: amd64
    #         os: Linux
    #         target: x86_64-unknown-freebsd
    steps:
      # Store the version, stripping any v-prefix
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Test in FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          run: |
            pwd
            ls -l
            uname -a
            pkg update && pkg install rust
            cargo -vV
