name: Test cross build

on:
  push:
    branches:
       - cross

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-freebsd:
    # needs: [create-release]
    runs-on:
      - self-hosted
      - Linux
      - X64
    steps:
      # Store the version, stripping any v-prefix
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Sync with FreeBSD
        run:
          rsync -rlptxzH -e ssh --del ./ freebsd:work/

      - name: Build on FreeBSD
        run:
          ssh freebsd 'cd work && cargo build --locked --release'

      - name: Copy binary to host
        run:
          scp work/target/release/defguard-proxy .
