name: Test cross build

on:
  push:
    branches:
       - cross

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    # needs: [create-release]
    runs-on:
      - self-hosted
      - Linux
      - X64
    steps:
      # Store the version, stripping any v-prefix
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Sync with FreeBSD
        run:
          pwd

      # - name: Build on FreeBSD
      #   run: |
      #     pwd
      #     ls -l
      #     uname -a
      #     pkg update && pkg install rust
      #     cargo -vV
      #     echo "${VERSION}"
