name: Lint frontend

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "web/**"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "web/**"

jobs:
  lint-web:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: install deps
        working-directory: ./web
        run: |
          npm i -g pnpm
          pnpm i --frozen-lockfile
      - name: Lint
        working-directory: ./web
        run: pnpm lint
