name: Lint frontend

on:
  push:
    branches:
      - dev
      - "release/**"
      - "stable/**"
    paths-ignore:
      - "*.md"
      - "LICENSE"
  pull_request:
    branches:
      - dev
      - "release/**"
      - "stable/**"
    paths-ignore:
      - "*.md"
      - "LICENSE"

jobs:
  lint-web:
    runs-on:
      - codebuild-defguard-proxy-runner-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Install NodeJS
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 26

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          package_json_file: web/package.json
          cache: true
          run_install: false

      - name: Install deps
        working-directory: web
        run: pnpm install --frozen-lockfile

      - name: Build translations
        working-directory: web
        run: pnpm dlx @inlang/paraglide-js compile --project ./project.inlang --outdir ./src/paraglide

      - name: Lint
        working-directory: web
        run: pnpm lint

      - name: Audit
        working-directory: web
        run: pnpm audit --prod --ignore-unfixable
