name: Lint frontend

on:
  push:
    branches:
      - main
      - dev
      - 'release/**'
    paths-ignore:
      - "*.md"
      - "LICENSE"
  pull_request:
    branches:
      - main
      - dev
      - 'release/**'
    paths-ignore:
      - "*.md"
      - "LICENSE"

jobs:
  lint-web:
    runs-on:
      - codebuild-defguard-proxy-runner-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: install deps
        working-directory: ./webnext
        run: |
          npm i -g pnpm
          pnpm i --frozen-lockfile
      - name: Lint
        working-directory: ./webnext
        run: pnpm lint
      - name: Audit
        working-directory: ./webnext
        run: pnpm audit --prod
