name: Make a new release
on:
  push:
    # REMOVE: test only
    branches:
       - cross
    tags:
      - v*.*.*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SQLX_OFFLINE: "1"

jobs:
  build-docker-release:
    # Ignore tags with -, like v1.0.0-alpha
    if: startsWith(github.ref, 'refs/tags/') && !contains(github.ref, '-')
    name: Build Release Docker image
    uses: ./.github/workflows/build-docker.yml
    with:
      tags: |
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=sha
      # Explicitly disable latest tag. It will be added otherwise.
      flavor: |
        latest=false

  build-docker-prerelease:
    # Only build tags with -, like v1.0.0-alpha
    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-')
    name: Build Pre-release Docker image
    uses: ./.github/workflows/build-docker.yml
    with:
      tags: |
        type=raw,value=pre-release
        type=semver,pattern={{version}}
        type=sha
      # Explicitly disable latest tag. It will be added otherwise.
      flavor: |
        latest=false

  create-release:
    name: create-release
    runs-on: self-hosted
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          draft: true
          generate_release_notes: true

      - name: Create test GitHub release
        uses: softprops/action-gh-release@v3
        if: github.ref_type != 'tag'
        with:
          draft: true
          name: test

  create-sbom:
    needs: [create-release, build-docker-release]
    uses: ./.github/workflows/sbom.yml
    with:
      upload_url: ${{ needs.create-release.outputs.upload_url }}

  build-web:
    runs-on:
      # - codebuild-defguard-proxy-runner-${{ github.run_id }}-${{ github.run_attempt }}
      - self-hosted
      - Linux
      - X64

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install NodeJS
        uses: actions/setup-node@v6
        node-version: 25

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true
          version: 10

      # Change to '--frozen-lockfile' once this gets fixed:
      # https://github.com/pnpm/action-setup/issues/40
      - name: Build frontend
        run: pnpm install --ignore-scripts --no-frozen-lockfile && pnpm build
        working-directory: web

  build-binaries:
    needs:
      - build-web
      - create-release
    runs-on:
      - self-hosted
      - ${{ matrix.os }}
      - X64
    strategy:
      fail-fast: false
      matrix:
        build: [linux, linux-arm64, freebsd]
        include:
          - build: linux
            arch: amd64
            os: Linux
            target: x86_64-unknown-linux-gnu
          - build: linux-arm64
            arch: arm64
            os: Linux
            target: aarch64-unknown-linux-gnu
          - build: freebsd
            arch: amd64
            os: Linux
            target: x86_64-unknown-freebsd
    steps:
      # Store the version, stripping any v-prefix
      - name: Write release version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Rust stable
        if: matrix.build == 'linux'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "aarch64-unknown-linux-gnu"

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Build release binary
        if: matrix.build == 'linux'
        run: cargo build --locked --release --target ${{ matrix.target }}

      - name: Cross-build release binary
        if: matrix.build == 'linux-arm64'
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
          PKG_CONFIG_SYSROOT_DIR: /usr/lib/aarch64-linux-gnu
        run: cargo build --locked --release --target ${{ matrix.target }}

      - name: Cross-build release binary
        if: matrix.build == 'freebsd'
        run: |
          rsync -rlptxzH -e 'ssh -l root' --del ./ freebsd:work/
          ssh root@freebsd 'cd work && cargo build --locked --release'
          scp root@freebsd:work/target/release/defguard-proxy defguard-proxy-${{ github.ref_name }}-${{ matrix.target }}

      - name: Rename binary
        run: mv target/${{ matrix.target }}/release/defguard-proxy defguard-proxy-${{ github.ref_name }}-${{ matrix.target }}

      - name: Tar
        run:
          tar -zcf defguard-proxy-${{ github.ref_name }}-${{ matrix.target }}.tar.gz \
            defguard-proxy-${{ github.ref_name }}-${{ matrix.target }}

      - name: Upload release archive
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: defguard-proxy-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
          asset_name: defguard-proxy-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
          asset_content_type: application/octet-stream

      - name: Build DEB package
        if: matrix.build == 'linux'
        uses: bpicode/github-action-fpm@master
        with:
          fpm_args:
            "defguard-proxy-${{ github.ref_name }}-${{ matrix.target }}=/usr/bin/defguard-proxy
            defguard-proxy.service=/usr/lib/systemd/system/defguard-proxy.service
            example-config.toml=/etc/defguard/proxy.toml"
          fpm_opts: "--architecture ${{ matrix.arch }} --debug --output-type deb --version ${{ env.VERSION }} --package defguard-proxy-${{ env.VERSION }}-${{ matrix.target }}.deb"

      - name: Upload DEB
        if: matrix.build == 'linux'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: defguard-proxy-${{ env.VERSION }}-${{ matrix.target }}.deb
          asset_name: defguard-proxy-${{ env.VERSION }}-${{ matrix.target }}.deb
          asset_content_type: application/octet-stream

      - name: Build RPM package
        if: matrix.build == 'linux'
        uses: bpicode/github-action-fpm@master
        with:
          fpm_args:
            "defguard-proxy-${{ github.ref_name }}-${{ matrix.target }}=/usr/bin/defguard-proxy
            defguard-proxy.service=/usr/lib/systemd/system/defguard-proxy.service
            example-config.toml=/etc/defguard/proxy.toml"
          fpm_opts: "--architecture ${{ matrix.arch }} --debug --output-type rpm --version ${{ env.VERSION }} --package defguard-proxy-${{ env.VERSION }}-${{ matrix.target }}.rpm"

      - name: Upload RPM
        if: matrix.build == 'linux'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: defguard-proxy-${{ env.VERSION }}-${{ matrix.target }}.rpm
          asset_name: defguard-proxy-${{ env.VERSION }}-${{ matrix.target }}.rpm
          asset_content_type: application/octet-stream

      - name: Build FreeBSD package
        if: matrix.build == 'freebsd'
        uses: bpicode/github-action-fpm@master
        with:
          fpm_args:
            "defguard-${{ github.ref_name }}-${{ matrix.target }}=/usr/local/bin/defguard-proxy
            defguard-proxy.service.freebsd=/usr/local/etc/rc.d/defguard-proxy
            example-config.toml=/etc/defguard/proxy.toml"
          fpm_opts: "--architecture ${{ matrix.arch }} --debug --output-type freebsd --version ${{ env.VERSION }} --package defguard-${{ env.VERSION }}_${{ matrix.target }}.pkg --freebsd-osversion '*' --depends openssl"

      - name: Upload FreeBSD
        if: matrix.build == 'freebsd'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: defguard-${{ env.VERSION }}_${{ matrix.target }}.pkg
          asset_name: defguard-${{ env.VERSION }}_${{ matrix.target }}.pkg
          asset_content_type: application/octet-stream
