name: Test backend

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "*.md"
      - "LICENSE"
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - "*.md"
      - "LICENSE"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: [self-hosted, Linux]
    container: rust:1

    steps:
      - name: Debug
        run: echo ${{ github.ref_name }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Install protoc
        run: apt-get update && apt-get -y install protobuf-compiler
      - name: Check format
        run: |
          rustup component add rustfmt
          cargo fmt -- --check
      - name: Run tests
        run: cargo test --locked --no-fail-fast
